In [1]:
import numpy as np

In [5]:
lamb = -1
1*(-lamb>=0 and -lamb<6)

1

In [7]:
a = 1, 
b = 2, 
c = []
c.append(a @ ... @ b)

TypeError: unsupported operand type(s) for @: 'tuple' and 'ellipsis'

In [12]:
import torch 

torch.diag(torch.tensor([1,2,3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [15]:
W = torch.rand(4,4)

diag = W.sum(1)
dhalf = torch.diag_embed(1. / torch.sqrt(torch.max(torch.ones(diag.size()), diag)))

In [18]:
torch.max(torch.ones(diag.size()), diag)

tensor([1.9736, 1.9527, 2.0727, 2.7565])

In [19]:
diag

tensor([1.9736, 1.9527, 2.0727, 2.7565])

In [24]:
from sklearn.decomposition import PCA
X = np.random.rand(100,55)
pca = PCA(n_components=5)
latent = pca.fit_transform(X)


In [26]:
print(latent.shape)

(100, 5)
